In [7]:
import nashpy as nash
import numpy as np

A = np.array([[0, 1, 3],
[3, 2, 0],
[1, 0, 1]])

rps = nash.Game(A)
rps

Zero sum game with payoff matrices:

Row player:
[[0 1 3]
 [3 2 0]
 [1 0 1]]

Column player:
[[ 0 -1 -3]
 [-3 -2  0]
 [-1  0 -1]]

In [ ]:
strat_1 = [1, 0, 0]
strat_2 = [0, 0.5, 0.5]

rps[strat_1, strat_2]

In [8]:
eqs = rps.support_enumeration()
list(eqs)

[(array([0.5, 0.5, 0. ]), array([0.5, 0. , 0.5])),
 (array([0.5, 0.5, 0. ]), array([-0.  ,  0.75,  0.25]))]